#!/usr/bin/python
"""
I build things by writing "built VERSION" in a file
named _echo
"""


from twisted.python.filepath import FilePath
import sys

version = sys.argv[1]

dump = FilePath(__file__).parent().child('_echo')
if not dump.exists():
    dump.setContent('')

content = dump.getContent()
dump.setContent(content + 'built echo project version %s\n' % version)
